[package]
name = "world-execute-me"
version = "0.1.0"
authors = ["YEOLLL <28512134+YEOLLL@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
